---
title: "GSEA"
output: html_document
---

```{r}
load("/data/msun/projects/pandas/geraldine/01_preprocess/preprocess_filtered.Rdata")
library(stringr)
library(tidyverse)
library(ggpubr)
library(ggthemes)
library(clusterProfiler)
library(org.Mm.eg.db)
library(ggplot2)
library(future)
plan(multisession, workers=12)
#for some function, every session needs acess to all data, 
#but future sets limits to the maximum acess data,
#so we need set: 
options(future.globals.maxSize = 10000 * 1024^2)# 1G

tissue.list <- names(dge.list)
condition_1 <- list(c("F_4_Sed","F_4_RW"),c("F_16_Sed","F_16_RW"),c("M_4_Sed","M_4_RW"),c("M_16_Sed","M_16_RW"),c("M_Sed","M_RW"),c("F_Sed","F_RW"))
condition_2<- list(c("F_4_Sed","F_16_Sed"),c("F_4_RW","F_16_RW"),c("M_4_Sed","M_16_Sed"),c("M_4_RW","M_16_RW"))
condition_3 <- list(c("M_4_Sed","F_4_Sed"),c("M_16_RW","F_16_RW"),c("M_16_Sed","F_16_Sed"),c("M_4_RW","F_4_RW"))
walktable <- rbind(expand_grid(filedir.list="deg_table_sedvsrw",condition.list=condition_1,tissue.list,outputdir.list="table_sedvsrw"),expand_grid(filedir.list="deg_table_mvsf",condition.list=condition_3,tissue.list,outputdir.list="table_mvsf"),expand_grid(filedir.list="deg_table_zt4vs16",condition.list=condition_2,tissue.list,outputdir.list="table_zt4vs16"))
```

#gsea: edger: go
```{r}
GSEAgo <- function(filedir,condition,tissue,outputdir){
  file <- paste(condition[1],condition[2],sep = "vs")
  inputdir <- str_c("/data/msun/projects/pandas/geraldine/02_DEG/edgeR/",filedir,"/",tissue,"/",tissue,file)
  df <- read.csv(paste(inputdir,"csv",sep = ".")) 
  geneList = df[,"logFC"]
  names(geneList) = as.character(df[,"gene_id"])
  geneList = sort(geneList, decreasing = TRUE)
  go <- gseGO(geneList     = geneList,
              OrgDb        = org.Mm.eg.db,
              keyType = "ENSEMBL",
              ont          = "ALL",
              minGSSize    = 10,
              maxGSSize    = 500,
              pvalueCutoff = 1,
              verbose      = FALSE,
              nPermSimple = 10000)
  outputad <- str_c("/data/msun/projects/pandas/geraldine/06_GSEA/edgeR/go/",outputdir,"/",tissue,"/",tissue,file)
  print(str_c(tissue,condition))
  write.csv(go,file = str_c(outputad,".csv"))
}
pwalk(walktable, ~ GSEAgo(..1,..2,..3,..4))
```

#gsea: edger : kegg
```{r}
library("AnnotationDbi")

GSEAKEGG <- function(filedir,condition,tissue,outputdir){
  file <- paste(condition[1],condition[2],sep = "vs")
  inputdir <- str_c("/data/msun/projects/pandas/geraldine/02_DEG/edgeR/",filedir,"/",tissue,"/",tissue,file)
  df <- read.csv(paste(inputdir,"csv",sep = ".")) 
  df$ENTREZID = mapIds(org.Mm.eg.db,
                    keys=df$gene_id, #Column containing Ensembl gene ids
                    column="ENTREZID",
                    keytype="ENSEMBL",
                    multiVals="first")
  geneList = df[,"logFC"]
  names(geneList) = as.character(df[,"ENTREZID"])
  geneList = sort(geneList, decreasing = TRUE)
  KEGG <- gseKEGG(geneList = geneList,
               organism = "mmu",
              keyType = "ncbi-geneid",
              minGSSize    = 10,
              maxGSSize    = 500,
              pvalueCutoff = 1,
              verbose      = FALSE,
              nPermSimple = 10000)
  outputad <- str_c("/data/msun/projects/pandas/geraldine/06_GSEA/edgeR/kegg/",outputdir,"/",tissue,"/",tissue,file)
  write.csv(KEGG,file = str_c(outputad,".csv"))
  print(str_c(tissue,condition))
}
pwalk(walktable, ~ GSEAKEGG(..1,..2,..3,..4))
```

#gsea: deseq : go 
```{r}
GSEAgo <- function(filedir,condition,tissue,outputdir){
  file <- paste(condition[1],condition[2],sep = "vs")
  inputdir <- str_c("/data/msun/projects/pandas/geraldine/02_DEG/DESeq2/",filedir,"/",tissue,"/",tissue,file)
  df <- read.csv(paste(inputdir,"csv",sep = ".")) 
  geneList = df[,"log2FoldChange"]#
  names(geneList) = as.character(df[,"gene_id"])
  geneList = sort(geneList, decreasing = TRUE)
  go <- gseGO(geneList     = geneList,
              OrgDb        = org.Mm.eg.db,
              keyType = "ENSEMBL",
              ont          = "ALL",
              minGSSize    = 10,
              maxGSSize    = 500,
              pvalueCutoff = 1,
              verbose      = FALSE,
              nPermSimple = 10000)
  outputad <- str_c("/data/msun/projects/pandas/geraldine/06_GSEA/DESeq2/go/",outputdir,"/",tissue,"/",tissue,file)
  write.csv(go,file = str_c(outputad,".csv"))
  print(str_c(tissue,condition))
}
pwalk(walktable, ~ GSEAgo(..1,..2,..3,..4))
```

#gsea: deseq : kegg
```{r}
library("AnnotationDbi")

GSEAKEGG <- function(filedir,condition,tissue,outputdir){
  file <- paste(condition[1],condition[2],sep = "vs")
  inputdir <- str_c("/data/msun/projects/pandas/geraldine/02_DEG/DESeq2/",filedir,"/",tissue,"/",tissue,file)
  df <- read.csv(paste(inputdir,"csv",sep = ".")) 
  df$ENTREZID = mapIds(org.Mm.eg.db,
                    keys=df$gene_id, #Column containing Ensembl gene ids
                    column="ENTREZID",
                    keytype="ENSEMBL",
                    multiVals="first")
  geneList = df[,"log2FoldChange"]
  names(geneList) = as.character(df[,"ENTREZID"])
  geneList = sort(geneList, decreasing = TRUE)
  KEGG <- gseKEGG(geneList = geneList,
               organism = "mmu",
              keyType = "ncbi-geneid",
              minGSSize    = 10,
              maxGSSize    = 500,
              pvalueCutoff = 1,
              verbose      = FALSE,
              nPermSimple = 10000)
  outputad <- str_c("/data/msun/projects/pandas/geraldine/06_GSEA/DESeq2/kegg/",outputdir,"/",tissue,"/",tissue,file)
  write.csv(KEGG,file = str_c(outputad,".csv"))
}
pwalk(walktable, ~ GSEAKEGG(..1,..2,..3,..4))
```

#make a combined table :go geneset
```{r}
myfuns <- function(x){
    df=read.csv(x,row.names = 1) %>% dplyr::select(5:9)
    filename=as.character(str_split(x, "/", simplify = TRUE)[,12]) 
    suffix=as.character(str_split(filename, "\\.", simplify = TRUE)[,1])
    colnames(df)=paste(paste(colnames(df),suffix,sep="_"),"edger",sep = "_")
    df <- df %>% rownames_to_column(var = "ID")
    return(df)
}
funs <- function(x){
    df=read.csv(x,row.names = 1) %>% dplyr::select(5:9)
    filename=as.character(str_split(x, "/", simplify = TRUE)[,12]) 
    suffix=as.character(str_split(filename, "\\.", simplify = TRUE)[,1])
    colnames(df)=paste(paste(colnames(df),suffix,sep="_"),"deseq2",sep = "_")
    df <- df %>% rownames_to_column(var = "ID")
    return(df)
}
dge.list <- dge.list %>% map(function(x){
  x$samples$col <- str_c(x$samples$Tissue,'_',x$samples$Sex,'_',x$samples$Group,'_ZT',x$samples$ZT)
  return(x)
})

combinealldata <- function(tissue){
  edger.sedrw <- list.files(path = paste("/data/msun/projects/pandas/geraldine/06_GSEA/edgeR/go/table_sedvsrw",tissue,sep = "/"),full.names = TRUE) %>% 
    map(myfuns) %>% purrr::reduce(inner_join, by = "ID")
  
  edger.zt <- list.files(path = paste("/data/msun/projects/pandas/geraldine/06_GSEA/edgeR/go/table_zt4vs16",tissue,sep = "/"), full.names = TRUE) %>% 
    map(myfuns) %>% purrr::reduce(inner_join, by = "ID")
  
  deseq.sedrw <- list.files(path = paste("/data/msun/projects/pandas/geraldine/06_GSEA/DESeq2/go/table_sedvsrw",tissue,sep = "/"), full.names = TRUE) %>% 
    map(funs) %>% purrr::reduce(inner_join, by = "ID")
  
  deseq.zt <- list.files(path = paste("/data/msun/projects/pandas/geraldine/06_GSEA/DESeq2/go/table_zt4vs16",tissue,sep = "/"), full.names = TRUE) %>% 
    map(funs) %>% purrr::reduce(inner_join, by = "ID")

    #go info
  go <- read.csv("/data/msun/projects/pandas/geraldine/06_GSEA/DESeq2/go/table_sedvsrw/BF/BFF_16_SedvsF_16_RW.csv",row.names = 1) %>% dplyr::select(1:4)
  #last merge
  data.list <- list(go,edger.sedrw,deseq.sedrw,edger.zt,deseq.zt)
  combined.table <- data.list %>% purrr::reduce(inner_join, by = "ID") 
  print(tissue)
  openxlsx::write.xlsx(combined.table,file =
              paste(paste("/data/msun/projects/pandas/geraldine/06_GSEA/combined_go",tissue,sep = "/"),".xlsx",sep = ""))
}

walk(names(dge.list), ~ combinealldata(.))
```

#make a combined table :kegg genset
```{r}
myfuns <- function(x){
    df=read.csv(x,row.names = 1) %>% dplyr::select(4:8)
    filename=as.character(str_split(x, "/", simplify = TRUE)[,12]) 
    suffix=as.character(str_split(filename, "\\.", simplify = TRUE)[,1])
    colnames(df)=paste(paste(colnames(df),suffix,sep="_"),"edger",sep = "_")
    df <- df %>% rownames_to_column(var = "ID")
    return(df)
}
funs <- function(x){
    df=read.csv(x,row.names = 1) %>% dplyr::select(4:8)
    filename=as.character(str_split(x, "/", simplify = TRUE)[,12]) 
    suffix=as.character(str_split(filename, "\\.", simplify = TRUE)[,1])
    colnames(df)=paste(paste(colnames(df),suffix,sep="_"),"deseq2",sep = "_")
    df <- df %>% rownames_to_column(var = "ID")
    return(df)
}
dge.list <- dge.list %>% map(function(x){
  x$samples$col <- str_c(x$samples$Tissue,'_',x$samples$Sex,'_',x$samples$Group,'_ZT',x$samples$ZT)
  return(x)
})

combinealldata <- function(tissue){
  edger.sedrw <- list.files(path = paste("/data/msun/projects/pandas/geraldine/06_GSEA/edgeR/kegg/table_sedvsrw",tissue,sep = "/"),full.names = TRUE) %>% 
    map(myfuns) %>% purrr::reduce(inner_join, by = "ID")
  
  edger.zt <- list.files(path = paste("/data/msun/projects/pandas/geraldine/06_GSEA/edgeR/kegg/table_zt4vs16",tissue,sep = "/"), full.names = TRUE) %>% 
    map(myfuns) %>% purrr::reduce(inner_join, by = "ID")
  
  deseq.sedrw <- list.files(path = paste("/data/msun/projects/pandas/geraldine/06_GSEA/DESeq2/kegg/table_sedvsrw",tissue,sep = "/"), full.names = TRUE) %>% 
    map(funs) %>% purrr::reduce(inner_join, by = "ID")
  
  deseq.zt <- list.files(path = paste("/data/msun/projects/pandas/geraldine/06_GSEA/DESeq2/kegg/table_zt4vs16",tissue,sep = "/"), full.names = TRUE) %>% 
    map(funs) %>% purrr::reduce(inner_join, by = "ID")

    #kegg info
  kegg <- read.csv("/data/msun/projects/pandas/geraldine/06_GSEA/DESeq2/kegg/table_sedvsrw/BF/BFF_16_SedvsF_16_RW.csv",row.names = 1) %>% dplyr::select(1:3)
  #last merge
  data.list <- list(kegg,edger.sedrw,deseq.sedrw,edger.zt,deseq.zt)
  combined.table <- data.list %>% purrr::reduce(inner_join, by = "ID") 
  print(tissue)
  openxlsx::write.xlsx(combined.table,file =
              paste(paste("/data/msun/projects/pandas/geraldine/06_GSEA/combined_kegg",tissue,sep = "/"),".xlsx",sep = ""))
}

walk(names(dge.list), ~ combinealldata(.))
```

